[package]
name = "cryptix_encryption"
version = "1.1.1"
edition = "2024"

[dependencies]
hmac = "0.12"
sha2 = "0.10"
base64 = "0.21"
rand = "0.8"
bitcoin_hashes = "0.11"
hkdf = "0.12"
tracing = "0.1"
tracing-subscriber = "0.3"
hex = "0.4"
subtle = "2.4"
lru = "0.11"
once_cell = "1.19"
